### PR TITLE
Add Linting

### PR DESCRIPTION
**Pull request by stephenmichaelf**
Are you OK with going down this road? It seems worthwhile to me for the consistency, quality, and safety. It will take time to do the initial work but then each PR worth of changes should be small.

They suggest LF line endings too, I changed those. Seems like GitHub may be ignoring that.

Some things that have been caught:
- Missing  semicolons
- Cyclomatic complexity
- Formatting
- Unresolved promise
- Unnecessary variables

My preference would be to do PRs every day or so and comment out the lint method call until its done. There are still a large number of things to fix but we need the code to build obviously.

This way we dont get one huge merge that is hard to review.

What do you think? Then we get in line with the security practices and code standards.

If you agree let me know and I can let you know when this is ready to merge for the day.

#39

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
I'm fine but Nyoman is higher pri

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stephenmichaelf** [comment]
What does Nyoman mean? :)

**Comment by bryanmacfarlane** [comment]
According to my phone type ahead, it means ntlm

**Comment by stephenmichaelf** [comment]
Let's discuss that when you can, there are more changes there than I thought.

This is ready for merge after you review.

One thing I am unsure of: in package-lock.json some of the integrity items changed to sha1-5, not sure why.

**Comment by bryanmacfarlane** [comment]
I like catching real issues (promise chains etc...) but lets be careful about high churn for low value rules (variable names etc...)

**Comment by stephenmichaelf** [comment]
I am going to get rid of this PR and we can start from a simple linting setup with high value options turned on. This one is too heavy handed with low ROI on some things.

**Pull request closed without merging**
