### PR TITLE
Accept error message in body as a string

### PR DESCRIPTION
**Pull request by mmajcica**
Solves #123

### CODE REVIEW

**Comment by damccorm** [comment]
This looks good to me, could you bump the version number in package.json to ```1.1.2```?

**Comment by damccorm** [comment]
Thanks for the quick turnaround/contribution! I'll go ahead and merge

**Comment by mmajcica** [comment]
Thanks, could you poke someone to publish it so that I can get the latest version in my project?

**Comment by damccorm** [comment]
@bryanmacfarlane can we publish this?

**Comment by stephenmichaelf** [comment]
I know its been merged but can we add a test for this?

**Comment by stephenmichaelf** [comment]
Thanks! I've reached out to our lead to ask for this to be published.

**Comment by mmajcica** [comment]
@stephenmichaelf @damccorm I added the test that validates my code. I would love to get this on npmjs as it will make my life easier. Could you again ask someone to publish a new version?

**Comment by damccorm** [comment]
We just published 1.1.2, sorry for the delay.

**Pull request merged**
