### PR TITLE
Added private token handler

### PR DESCRIPTION
**Pull request by mmajcica**
Several tools, like Gitlab, do support authentication through the Private-Token header field and related PAT.
Check this for further info https://docs.gitlab.com/ee/api/#personal-access-tokens 

I created a new handler that will do just that.

### CODE REVIEW

**Comment by damccorm** [comment]
I'm not very familiar with this so I need to do a little more research on this to understand its usage so that I can give a good review. In the meantime, a couple things that could be helpful:

1) I'm struggling to find any tools besides GitLab that use the `Private-Token` header. If its just GitLab I'd probably be more inclined to just encourage users to use the additional-headers parameter and pass it in, but it sounds like other things use it as well - could you point me to an example or 2?
2) An export needs to be added [here](https://github.com/Microsoft/typed-rest-client/blob/e2b762f6849d2b2b4eb51198efaf999c411deb06/lib/Handlers.ts).
3) Could you add a simple test to confirm this does what its supposed to? I know we don't have testing for other handlers, but [we want to](https://github.com/Microsoft/typed-rest-client/issues/90) and I'd rather start that now. It probably belongs in a separate file [test/units](https://github.com/Microsoft/typed-rest-client/tree/master/test/units)/handlers

**Comment by mmajcica** [comment]
@damccorm you are tight, not many tools are still using it. Aside of Gitlab, there is gitswarm that I do know about. However, it is not much code and can be an option. If you think it is a clutter, I'm also fine to keep it only in my projects.
I do agree about the tests and I would like to give it a try. Once you decide if to keep this, then I'll add test to the same PR, otherwise I'll go with a separate one for the tests.

**Comment by damccorm** [comment]
I think lets keep this separate from the library. Since we allow people to pass in custom handlers I think it makes sense to keep this lib to more standard/universal handler types so that we can keep it tight and small. With that said, if you disagree/think this will be useful for other people you could also publish it as your own stand-alone npm package, I think that's probably a good pattern for us to use with handlers in general.

**Comment by mmajcica** [comment]
I agree with that.

**Pull request closed without merging**
