### PR TITLE
Fix proxy if password has url sensitive characters

### PR DESCRIPTION
**Pull request by omeshp**

### CODE REVIEW

**Comment by omeshp** [comment]
#49

**Comment by TingluoHuang** [comment]
what will happen when my password contains any of these `;,/?:@&=+$`, like `http://user:pass?word@github.com`

**Comment by omeshp** [comment]
@TingluoHuang tunnel library doesn't send password as a part of URL, it's set in header.

**Comment by TingluoHuang** [comment]
Looks good to me.  thanks for finding and fixing this!

**Comment by bryanmacfarlane** [comment]
+1 - I can release after you merge

**Pull request merged**
