### PR TITLE
Handle 303 SeeOther redirect.

### PR DESCRIPTION
**Pull request by williambernardet**
Implementation is missing 303 redirect support.

I am facing issue downloading a file from a resource which is using this redirect to point to the actual resource.

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
This looks like a good addition.  Thanks so much.  @stephenmichaelf - agree?

**Comment by bryanmacfarlane** [comment]
@williambernardet - cla ok?

**Comment by williambernardet** [comment]
Just signed it

**Comment by stephenmichaelf** [comment]
This looks great! Thanks for taking the time to make a contribution @williambernardet :)

**Comment by stephenmichaelf** [comment]
Could we add a test where it redirects to a page that gets a 404 or something? To make sure failure cases are handled correctly after redirect.

**Comment by bryanmacfarlane** [comment]
released as 1.0.9

**Pull request merged**
