### PR TITLE
Fix security warnings

### PR DESCRIPTION
**Pull request by damccorm**
Right now we're getting flagged for a bunch of security warnings. This fixes some of them

### CODE REVIEW

**Comment by stephenmichaelf** [comment]
Did you manually change the package-lock?

**Comment by damccorm** [comment]
I used `npm audit --fix` - npm automatically manages these. It didn't fix all of the issues because of incompatibilities, but these ones didn't cause any issues

**Comment by stephenmichaelf** [comment]
Is that going to break when we make future updates to package versions?

**Comment by damccorm** [comment]
No, the package-lock won't change unless a new package version is introduced that requires it to. So not unless we explicitly introduce a dependency on a lower version of one of these things

**Pull request merged**
